--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/VennDev/VPlayerDataSaver
build-by-default: true
branches:
- main
projects:
  VPlayerDataSaver:
    path: ""
    libs:
      - src: VennDev/LibVapmPMMP/LibVapmPMMP
        version: ^2.3.5
        branch: "main"
      - src: VennDev/VapmDatabasePMMP/VapmDatabasePMMP
        version: ^2.0
        branch: "main"
...
