---
name: VPlayerDataSaver
main: venndev\vplayerdatasaver\VPlayerDataSaver
version: 1.0
api: 5.0.0
author: VennDev
description: A simple plugin that logs the player's data to a database or YAML file.
...